@extends('layouts.app')

@section('content')
    <!-- Banner Section -->
    <section class="banner slide-in-right">
        <div class="currency-card" style="flex: 0.6;">
            <h2>Currency Exchange Rates</h2>
            <!-- Search Input -->
            <div class="currency-search">
                <input type="text" id="currency-search" placeholder="Search currencies..." />
                <i class="fas fa-search"></i>
            </div>
            <div class="currency-table">
                <div class="currency-header">
                    <span>Currency</span>
                    <span>Buy</span>
                    <span>Sell</span>
                </div>
                <div id="currency-rates">
                    <!-- Dynamic content will be inserted here -->
                </div>
            </div>
        </div>
        <!-- Larger announcement slider -->
        <div class="announcement-slider" style="flex: 1.4; height: 400px;">
            <div class="slider-container" style="height: 100%;">
                @foreach($announcements as $index => $announcement)
                    <div class="slide {{ $index === 0 ? 'active' : '' }}">
                        <img src="{{ $announcement->image }}" alt="{{ $announcement->title }}">
                        <div class="slide-content">
                            <h2>{{ $announcement->title }}</h2>
                            <p>{{ $announcement->description }}</p>
                            <button class="slide-btn">{{ $announcement->button_text }}</button>
                        </div>
                    </div>
                @endforeach
            </div>
            <div class="slider-controls">
                <button class="prev-slide"><i class="fas fa-chevron-left"></i></button>
                <div class="slider-dots">
                    @foreach($announcements as $index => $announcement)
                        <span class="dot {{ $index === 0 ? 'active' : '' }}"></span>
                    @endforeach
                </div>
                <button class="next-slide"><i class="fas fa-chevron-right"></i></button>
            </div>
        </div>
    </section>

    <!-- Quick Links Section -->
    <div class="quick-links">
        <br>
        <hr>
        <br>
        <div class="quick-links-slider">
            <div class="links-wrapper">
                @foreach($quickLinks as $link)
                    <div class="link-card" style="background: linear-gradient(135deg, {{ $link->color1 }}, {{ $link->color2 }});">
                        <i class="fas {{ $link->icon }}"></i>
                        <p>{{ $link->title }}</p>
                    </div>
                @endforeach
            </div>
        </div>
        <div class="quick-links-nav">
            <button class="prev-links"><i class="fas fa-chevron-left"></i></button>
            <div class="nav-dots">
                @for($i = 0; $i < ceil(count($quickLinks) / 4); $i++)
                    <span class="nav-dot {{ $i === 0 ? 'active' : '' }}"></span>
                @endfor
            </div>
            <button class="next-links"><i class="fas fa-chevron-right"></i></button>
        </div>
    </div>

    <!-- Two Column Layout -->
    <div class="two-column">
        <!-- Left Column -->
        <div class="column left-column">
            <!-- Events Section -->
            <section class="events slide-in-left">
                <h2 class="section-title">Events <i class="fas fa-calendar-alt"></i></h2>
                <div class="calendar">
                    <div class="calendar-header">
                        <button class="cal-nav prev"><i class="fas fa-chevron-left"></i></button>
                        <h3 class="current-month">{{ date('F Y') }}</h3>
                        <button class="cal-nav next"><i class="fas fa-chevron-right"></i></button>
                    </div>
                    <div class="calendar-grid" id="calendar-grid">
                        <!-- Calendar will be generated by JavaScript -->
                    </div>
                </div>
                <!-- Nearest Upcoming Events -->
                <div class="nearest-events">
                    <h3>UPCOMING EVENTS</h3>
                    <div class="nearest-event-list" id="nearest-event-list">
                        @foreach($nearestEvents as $event)
                            <div class="nearest-event">
                                <div class="nearest-event-date">
                                    <div class="date-box">{{ $event->date->format('d') }}</div>
                                    <div class="month">{{ $event->date->format('M') }}</div>
                                </div>
                                <div class="nearest-event-details">
                                    <h4>{{ $event->title }}</h4>
                                    <p>{{ $event->time }} - {{ $event->location }}</p>
                                </div>
                                <div class="nearest-event-actions">
                                    <button class="nearest-event-btn">RSVP</button>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </section>

            <!-- Documents Section -->
            <section class="documents fade-in" id="documents">
                <h2 class="section-title">Documents <i class="fas fa-file-alt"></i></h2>
                <div class="document-list">
                    @foreach($documents as $document)
                        <div class="document">
                            @if($document->type === 'pdf')
                                <i class="fas fa-file-pdf document-icon"></i>
                            @elseif($document->type === 'excel')
                                <i class="fas fa-file-excel document-icon"></i>
                            @elseif($document->type === 'word')
                                <i class="fas fa-file-word document-icon"></i>
                            @else
                                <i class="fas fa-file document-icon"></i>
                            @endif
                            <div class="document-details">
                                <h4>{{ $document->title }}</h4>
                                <p>Updated: {{ $document->updated_date->format('M d, Y') }}</p>
                            </div>
                            <a href="{{ Storage::url($document->file) }}" class="download-btn" download>
                                <i class="fas fa-download"></i>
                            </a>
                        </div>
                    @endforeach
                </div>
                @if($documents->count() > 3)
                    <button class="view-all">View all documents</button>
                @endif
            </section>
        </div>

        <!-- Right Column -->
        <div class="column right-column">
            <!-- Contacts Section -->
            <section class="contacts slide-in-right" id="contacts">
                <h2 class="section-title">Contacts <i class="fas fa-address-book"></i></h2>
                <!-- Search Input -->
                <div class="search-contacts">
                    <input type="text" id="contact-search" placeholder="Search by name, email, phone, or department..." />
                    <i class="fas fa-search"></i>
                </div>
                <!-- Contact List -->
                <div class="contact-list" id="contact-list">
                    @foreach($contacts as $contact)
                        <div class="contact" data-name="{{ $contact->name }}" data-email="{{ $contact->email }}" data-phone="{{ $contact->phone }}" data-department="{{ $contact->department }}">
                            <img src="{{ $contact->photo ? $contact->photo : asset('images/pr.jpeg') }}" alt="Contact" class="contact-img">
                            <div class="contact-details">
                                <h4>{{ $contact->name }}</h4>
                                <p><i class="fas fa-phone"></i> {{ $contact->phone }}</p>
                                <p><i class="fas fa-envelope"></i> {{ $contact->email }}</p>
                                <p><i class="fas fa-building"></i> {{ $contact->department }}</p>
                            </div>
                            <button class="contact-action"><i class="fas fa-ellipsis-v"></i></button>
                        </div>
                    @endforeach
                </div>
                @if($contacts->count() > 3)
                    <button class="view-all">View all contacts</button>
                @endif
            </section>
            
            <!-- Leaderboard Section -->
            <section class="leaderboard fade-in">
                <h2 class="section-title">Leaderboard <i class="fas fa-trophy"></i></h2>
                <div class="leaderboard-content">
                    <h3>Fastest and Well-trained Employees for {{ date('Y') }}</h3>
                    @foreach($leaderboards as $index => $leader)
                        <div class="leaderboard-item">
                            <div class="rank">{{ $index + 1 }}</div>
                            <img src="{{ $leader->photo ? $leader->photo : asset('images/pr.jpeg') }}" alt="Employee" class="employee-img">
                            <div class="employee-details">
                                <h4>{{ $leader->name }}</h4>
                                <p>{{ $leader->department }}</p>
                            </div>
                            <div class="score">{{ $leader->score }}<span>pts</span></div>
                        </div>
                    @endforeach
                </div>
            </section>

            <!-- Invitations Section -->
            <section class="invitations slide-in-left">
                <h2 class="section-title">Invitations <i class="fas fa-envelope-open-text"></i></h2>
                <div class="invitation-list">
                    @foreach($invitations as $invitation)
                        <div class="invitation">
                            <div class="invitation-icon">
                                <i class="fas {{ $invitation->icon }}"></i>
                            </div>
                            <div class="invitation-details">
                                <h4>{{ $invitation->title }}</h4>
                                <p>{{ $invitation->description }}</p>
                                <div class="invitation-actions">
                                    <button class="accept-btn">{{ $invitation->button_text }}</button>
                                    <button class="decline-btn">Decline</button>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
            </section>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        // Your JavaScript from the original file
        // Make sure to update API URLs to use Laravel routes
    </script>
@endpush